theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/AJARProject/AJUI_Progressbar/archive/master.zip
  tar_url: https://github.com/AJARProject/AJUI_Progressbar/archive/master.tar.gz
